version: '3.1'

services:

  db:
    build:
      context: "db/"
      args:
        - USERNAME=${DB_USERNAME}
        - PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - /home/yevhenii/database:/var/lib/postgresql/data
    ports:
     - "${DB_OUTER_PORT}:${DB_INNER_PORT}"

  backend:
    build: "./"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_INNER_PORT}/ft
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_SHOW: ${SPRING_JPA_SHOW}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      FT_TOKEN_SECRET: ${FT_TOKEN_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
    - db
    
  frontend:
    build: "./webclient"
    ports:
    - "80:80"
    depends_on:
    - backend

