server:
  contextPath: /ft

#
# [ Database Configuration Section ]
#
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ft
    driver-class-name: org.postgresql.Driver
    username: romm
    password: romm
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgresPlusDialect

#
# Logging
#
logging:
  level:
    #org.springframework.web: ERROR
    com.ft: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    #file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  #file: /Users/mkyong/application.log